--- #YAML:1.0
name:                Net-Lorcon
version:             0.02
abstract:            Raw wireless packet injection using the Lorcon library
license:             perl
author:              
    - David Leadbeater <dgl@dgl.cx>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Copy:                    0
    File::Spec:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
